# Generated by Django 5.0.6 on 2024-06-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chaivariety',
            name='price',
            field=models.SmallIntegerField(default=10.0),
        ),
    ]
